// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

pub type BOOL = i32;
pub mod Windows {
    pub mod Win32 {
        pub mod System {
            pub mod Threading {
                windows_link::link!("kernel32.dll" "system" fn IsProcessorFeaturePresent(processorfeature : PROCESSOR_FEATURE_ID) -> super::super::super::super::BOOL);
                pub const PF_ARM_V8_CRYPTO_INSTRUCTIONS_AVAILABLE: PROCESSOR_FEATURE_ID = 30u32;
                pub type PROCESSOR_FEATURE_ID = u32;
            }
        }
    }
}
