name: ci
permissions:
  contents: read
on:
  pull_request:
  push:
jobs:
  # Intentionally excludes benchmarks for build performance reasons.
  test:
    # Don't run duplicate `push` jobs for the repo owner's PRs.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ${{ matrix.host_os }}

    env:
      CC_ENABLE_DEBUG_OUTPUT: 1

    strategy:
      matrix:
        # XXX: See `test-features` below.
        features:
          - # Default

        target:
          - aarch64-pc-windows-msvc

        mode:
          - --release

        rust_channel:
          - stable
          # Keep in sync with Cargo.toml and similar `rust_channel` sections.
          - 1.66.0 # MSRV
          - 1.67.0 # MSRV
          - 1.68.0 # MSRV
          - 1.69.0 # MSRV
          - 1.70.0 # MSRV
          - 1.71.0 # MSRV
          - 1.72.0 # MSRV
          - 1.73.0 # MSRV
          - 1.74.0 # MSRV
          - 1.75.0 # MSRV
          - 1.76.0 # MSRV
          - 1.77.0 # MSRV
          - 1.78.0 # MSRV
          - 1.79.0 # MSRV
          - 1.80.0 # MSRV
          - 1.81.0 # MSRV
          - 1.82.0 # MSRV
          - 1.83.0 # MSRV
          - 1.84.0 # MSRV
          - 1.85.0 # MSRV
          - 1.86.0 # MSRV
          - 1.87.0 # MSRV

        include:
          - target: aarch64-pc-windows-msvc
            host_os: windows-11-arm

    steps:
      - if: ${{ contains(matrix.host_os, 'ubuntu') }}
        run: sudo apt-get update -y

      - uses: briansmith/actions-checkout@v4
        with:
          persist-credentials: false

      # From https://github.com/actions/partner-runner-images/issues/77
      - if: ${{ contains(matrix.host_os, 'windows') && contains(matrix.host_os, 'arm') }}
        run: |
          curl -LOs https://static.rust-lang.org/rustup/dist/aarch64-pc-windows-msvc/rustup-init.exe
            ./rustup-init.exe -y --default-toolchain none --no-modify-path
          echo "$USERPROFILE/.cargo/bin" >> "$GITHUB_PATH"
        shell: sh

      - run: mk/install-build-tools.sh +${{ matrix.rust_channel }} --target=${{ matrix.target }}
        shell: sh

      - if: ${{ contains(matrix.host_os, 'windows') && contains(matrix.target, '86') }}
        run: ./mk/install-build-tools.ps1

      - if: ${{ matrix.xcode_version != '' }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode_version }}.app

      - if: ${{ !contains(matrix.host_os, 'windows') }}
        run: |
          mk/cargo.sh +${{ matrix.rust_channel }} test -vv --target=${{ matrix.target }} ${{ matrix.cargo_options }} ${{ matrix.features }} ${{ matrix.mode }}

      - if: ${{ contains(matrix.host_os, 'windows') }}
        run: |
          cargo +${{ matrix.rust_channel }} test -vv --target=${{ matrix.target }} ${{ matrix.cargo_options }} ${{ matrix.features }} ${{ matrix.mode }}

      # Check that all the needed symbol renaming was done.
      # TODO: Do this check on Windows too.

      - if: ${{ (matrix.target != 'aarch64-apple-ios' || matrix.rust_channel != '1.66.0') &&
                !contains(matrix.host_os, 'windows') }}
        run: rustup toolchain install --component=llvm-tools-preview ${{ matrix.rust_channel }}

      - if: ${{ (matrix.target != 'aarch64-apple-ios' || matrix.rust_channel != '1.66.0') &&
                !contains(matrix.host_os, 'windows') }}
        run: mk/check-symbol-prefixes.sh +${{ matrix.rust_channel }} --target=${{ matrix.target }}
